# Generated by Django 2.1.7 on 2019-06-10 10:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userprofiles', '0002_delete_applicationfordiploma'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThesisApplication',
            fields=[
                ('submitter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Φοιτητής')),
                ('semester', models.CharField(max_length=5, verbose_name='Τρέχον Εξάμηνο:')),
                ('left_lessons', models.CharField(blank=True, max_length=200, null=True, verbose_name='Υπολοιπόμενα Μαθήματα:')),
            ],
            options={
                'verbose_name': 'Αίτηση',
                'verbose_name_plural': 'Αιτήσεις',
            },
        ),
    ]
