# Starter pipeline
- task: UsePythonVersion
  inputs:
    versionSpec: '3.x'
    addToPath: true
- task: CmdLine
  inputs:
    script: 'pip install -r requirements.txt'
- task: ArchiveFiles
  inputs:
    rootFolderOrFile: '$(Build.BinariesDirectory)'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true