# Generated by Django 2.1.7 on 2019-06-10 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApplicationForDiploma',
        ),
    ]
