# Generated by Django 2.1.9 on 2019-06-17 10:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userprofiles', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentApplication',
            fields=[
                ('submitter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Φοιτητής')),
                ('topic', models.CharField(max_length=200, verbose_name='Τίτλος Πτυχιακής:')),
            ],
            options={
                'verbose_name': 'Ανάθεση',
                'verbose_name_plural': 'Αναθέσεις',
            },
        ),
    ]
